install:
  # Install on Ubuntu
  - git clone https://github.com/htacg/tidy-html5.git
  - cd tidy-html5
  - cd build/cmake
  - cmake ../..
  - cmake --build . --config Release
  - sudo make install
  - cd ../../..
  - echo $PWD

script:
  - bash tidy-travis.sh