install:
  # Install and build on Ubuntu:
  # https://codeyarns.com/2016/06/06/how-to-build-and-install-html-tidy/
  - git clone https://github.com/htacg/tidy-html5.git
  - cd tidy-html5
  - cd build/cmake
  - cmake ../..
  - cmake --build . --config Release
  - sudo make install
  - cd ../../..

script:
  - cd output && bash ../tidy.sh