install:
  - choco install html-tidy -y -i
  - reg add "HKCU\Software\Microsoft\Command Processor" /v AutoRun /t REG_EXPAND_SZ /d "chcp 65001" /f

build_script:
  - tidy -mq SashaBeautiful.html	+      chcp 65001
  - tidy -mq -utf8 СашаПрекрасна.html
